version: '3'

services:
  consensx-server:
    image: derpuntigamer/consensx
    ports:
      - 8080:8000
    depends_on:
      - consensx-db
    links:
      - consensx-db
    volumes:
      - /usr/src/app/consensx.itk.ppke.hu/media

  consensx-db:
    image: postgres:11.1
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=consensxuser
    - POSTGRES_DB=consensx